name = "wg-embedded-cortex-a"
subteam-of = "wg-embedded"
wg = true

[people]
leads = []
members = [
    "raw-bin",
    "andre-richter",
    "parched",
    "wizofe"
]

[website]
name = "Embedded Cortex-A team"
description = "Develops and maintains the core of the Cortex-A crate ecosystem "

[github]
orgs = ["rust-lang"]
