name = "wg-embedded-msp430"
subteam-of = "wg-embedded"
wg = true

[people]
leads = []
members = [
    "pftbest",
    "cr1901",
    "awygle",
]

[website]
name = "Embedded MSP430 team"
description = "Develops and maintains the core of the embedded MSP430 crate ecosystem"

[github]
orgs = ["rust-lang"]
