name = "wg-embedded-riscv"
subteam-of = "wg-embedded"
wg = true

[people]
leads = []
members = [
    "pftbest",
    "cr1901",
    "awygle",
]

[website]
name = "Embedded RISCV team"
description = "Develops and maintains the core of the embedded RISCV crate ecosystem"

[github]
orgs = ["rust-lang"]
