name = "wg-embedded-linux"
subteam-of = "wg-embedded"
wg = true

[people]
leads = []
members = [
    "posborne",
    "ryankurte",
    "nastevens",
]

[website]
name = "Embedded Linux team"
description = "Develops and maintains the core of the embedded Linux crate ecosystem"

[github]
orgs = ["rust-lang"]
