name = "wg-embedded-core"
subteam-of = "wg-embedded"
wg = true

[people]
leads = []
members = [
    "jamesmunns",
    "therealprof",
    "japaric",
]

[website]
name = "Embedded core team"
description = "The core team represents the WG in meetings with the Rust teams"

[github]
orgs = ["rust-lang"]
